
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
Prisma.prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AdminScalarFieldEnum = {
  id: 'id',
  first_name: 'first_name',
  last_name: 'last_name',
  password: 'password',
  mobile_number: 'mobile_number',
  country_code: 'country_code',
  email: 'email',
  location: 'location',
  joining_date: 'joining_date',
  role_id: 'role_id',
  status: 'status',
  avatar: 'avatar',
  employee_id: 'employee_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Admin_dismissedScalarFieldEnum = {
  id: 'id',
  first_name: 'first_name',
  last_name: 'last_name',
  password: 'password',
  mobile_number: 'mobile_number',
  country_code: 'country_code',
  email: 'email',
  is_super_admin: 'is_super_admin',
  location: 'location',
  joining_date: 'joining_date',
  role: 'role',
  employee_id: 'employee_id',
  x_primary_key: 'x_primary_key',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.System_configScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.IconScalarFieldEnum = {
  id: 'id',
  name: 'name',
  bucket_key: 'bucket_key',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.VerticalScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.ClientScalarFieldEnum = {
  id: 'id',
  name: 'name',
  client_display_id: 'client_display_id',
  organization_name: 'organization_name',
  country: 'country',
  state: 'state',
  email: 'email',
  password: 'password',
  mobile_number: 'mobile_number',
  country_code: 'country_code',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at',
  vertical_id: 'vertical_id',
  profile_pic: 'profile_pic'
};

exports.Prisma.Client_deletedScalarFieldEnum = {
  id: 'id',
  name: 'name',
  client_display_id: 'client_display_id',
  organization_name: 'organization_name',
  country: 'country',
  state: 'state',
  email: 'email',
  mobile_number: 'mobile_number',
  country_code: 'country_code',
  vertical_id: 'vertical_id',
  vertical_name: 'vertical_name',
  profile_pic: 'profile_pic',
  x_primary_key: 'x_primary_key',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Faq_categoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  name_normalized: 'name_normalized',
  icon_id: 'icon_id',
  vertical_id: 'vertical_id',
  description: 'description',
  status: 'status',
  index: 'index',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Faq_questionScalarFieldEnum = {
  id: 'id',
  question: 'question',
  answer: 'answer',
  publishing_status: 'publishing_status',
  status: 'status',
  attachments: 'attachments',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Faq_question_categoryScalarFieldEnum = {
  id: 'id',
  question_id: 'question_id',
  category_id: 'category_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  name_normalized: 'name_normalized',
  is_super_admin: 'is_super_admin',
  permissions_json: 'permissions_json',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.BoxScalarFieldEnum = {
  id: 'id',
  name: 'name',
  box_display_id: 'box_display_id',
  vertical_id: 'vertical_id',
  client_id: 'client_id',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at',
  vehicle_number: 'vehicle_number',
  connection_employee_id: 'connection_employee_id'
};

exports.Prisma.RestaurantScalarFieldEnum = {
  id: 'id',
  name: 'name',
  client_id: 'client_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  city: 'city',
  google_place_id: 'google_place_id',
  latitude: 'latitude',
  line_one: 'line_one',
  line_two: 'line_two',
  longitude: 'longitude',
  pincode: 'pincode',
  state: 'state',
  status: 'status'
};

exports.Prisma.Vertical_food_employeeScalarFieldEnum = {
  id: 'id',
  first_name: 'first_name',
  last_name: 'last_name',
  country_code: 'country_code',
  mobile_number: 'mobile_number',
  email: 'email',
  password: 'password',
  employee_display_id: 'employee_display_id',
  joining_date: 'joining_date',
  client_id: 'client_id',
  restaurant_id: 'restaurant_id',
  role: 'role',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at',
  profile_pic: 'profile_pic'
};

exports.Prisma.Vertical_food_employee_boxScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  box_id: 'box_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  status: 'status',
  access: 'access'
};

exports.Prisma.Restaurant_boxScalarFieldEnum = {
  id: 'id',
  restaurant_id: 'restaurant_id',
  box_id: 'box_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  status: 'status'
};

exports.Prisma.Vertical_food_employee_deletedScalarFieldEnum = {
  id: 'id',
  first_name: 'first_name',
  last_name: 'last_name',
  country_code: 'country_code',
  mobile_number: 'mobile_number',
  email: 'email',
  employee_display_id: 'employee_display_id',
  joining_date: 'joining_date',
  client_name: 'client_name',
  role_name: 'role_name',
  created_at: 'created_at',
  updated_at: 'updated_at',
  profile_pic: 'profile_pic',
  client_id: 'client_id',
  x_primary_key: 'x_primary_key'
};

exports.Prisma.Restaurant_deletedScalarFieldEnum = {
  id: 'id',
  name: 'name',
  client_id: 'client_id',
  client_name: 'client_name',
  manager_id: 'manager_id',
  manager_name: 'manager_name',
  city: 'city',
  google_place_id: 'google_place_id',
  latitude: 'latitude',
  line_one: 'line_one',
  line_two: 'line_two',
  longitude: 'longitude',
  pincode: 'pincode',
  state: 'state',
  x_primary_key: 'x_primary_key',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Box_deletedScalarFieldEnum = {
  id: 'id',
  name: 'name',
  box_display_id: 'box_display_id',
  vertical_id: 'vertical_id',
  vertical_name: 'vertical_name',
  client_id: 'client_id',
  client_name: 'client_name',
  vehicle_number: 'vehicle_number',
  x_primary_key: 'x_primary_key',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Vertical_food_consumerScalarFieldEnum = {
  id: 'id',
  full_name: 'full_name',
  country_code: 'country_code',
  phone: 'phone',
  status: 'status',
  client_id: 'client_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Vertical_food_consumer_boxScalarFieldEnum = {
  id: 'id',
  consumer_id: 'consumer_id',
  box_id: 'box_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Box_lockScalarFieldEnum = {
  id: 'id',
  box_id: 'box_id',
  lock_status: 'lock_status',
  created_at: 'created_at',
  updated_status: 'updated_status'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  client_id: 'client_id',
  box_id: 'box_id',
  box_display_id: 'box_display_id',
  box_name: 'box_name',
  restaurant_name: 'restaurant_name',
  type: 'type',
  title: 'title',
  description: 'description',
  is_read: 'is_read',
  is_dismissed: 'is_dismissed',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Box_telemetry_latestScalarFieldEnum = {
  id: 'id',
  box_id: 'box_id',
  health_status: 'health_status',
  power_status: 'power_status',
  battery_percentage: 'battery_percentage',
  memory_percentage: 'memory_percentage',
  ext_temp: 'ext_temp',
  zone1_temp: 'zone1_temp',
  zone2_temp: 'zone2_temp',
  ioniser_status: 'ioniser_status',
  adas_status: 'adas_status',
  bluetooth_status: 'bluetooth_status',
  camera_status: 'camera_status',
  gps_status: 'gps_status',
  gyrosensor_status: 'gyrosensor_status',
  port_big_status: 'port_big_status',
  port_small_status: 'port_small_status',
  save_to_memory_status: 'save_to_memory_status',
  sim_status: 'sim_status',
  solar_status: 'solar_status',
  turn_signal_status: 'turn_signal_status',
  wifi_status: 'wifi_status',
  advert_screen_status: 'advert_screen_status',
  dual_zone_status: 'dual_zone_status',
  connection_status: 'connection_status',
  updated_at: 'updated_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.adminOrderByRelevanceFieldEnum = {
  id: 'id',
  first_name: 'first_name',
  last_name: 'last_name',
  password: 'password',
  mobile_number: 'mobile_number',
  country_code: 'country_code',
  email: 'email',
  location: 'location',
  role_id: 'role_id',
  avatar: 'avatar',
  employee_id: 'employee_id'
};

exports.Prisma.admin_dismissedOrderByRelevanceFieldEnum = {
  id: 'id',
  first_name: 'first_name',
  last_name: 'last_name',
  password: 'password',
  mobile_number: 'mobile_number',
  country_code: 'country_code',
  email: 'email',
  location: 'location',
  role: 'role',
  employee_id: 'employee_id',
  x_primary_key: 'x_primary_key'
};

exports.Prisma.system_configOrderByRelevanceFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value'
};

exports.Prisma.iconOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  bucket_key: 'bucket_key'
};

exports.Prisma.verticalOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.clientOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  client_display_id: 'client_display_id',
  organization_name: 'organization_name',
  country: 'country',
  state: 'state',
  email: 'email',
  password: 'password',
  mobile_number: 'mobile_number',
  country_code: 'country_code',
  vertical_id: 'vertical_id',
  profile_pic: 'profile_pic'
};

exports.Prisma.client_deletedOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  client_display_id: 'client_display_id',
  organization_name: 'organization_name',
  country: 'country',
  state: 'state',
  email: 'email',
  mobile_number: 'mobile_number',
  country_code: 'country_code',
  vertical_id: 'vertical_id',
  vertical_name: 'vertical_name',
  profile_pic: 'profile_pic',
  x_primary_key: 'x_primary_key'
};

exports.Prisma.faq_categoryOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  name_normalized: 'name_normalized',
  icon_id: 'icon_id',
  vertical_id: 'vertical_id',
  description: 'description'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.faq_questionOrderByRelevanceFieldEnum = {
  id: 'id',
  question: 'question',
  answer: 'answer'
};

exports.Prisma.faq_question_categoryOrderByRelevanceFieldEnum = {
  id: 'id',
  question_id: 'question_id',
  category_id: 'category_id'
};

exports.Prisma.roleOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  name_normalized: 'name_normalized'
};

exports.Prisma.boxOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  box_display_id: 'box_display_id',
  vertical_id: 'vertical_id',
  client_id: 'client_id',
  vehicle_number: 'vehicle_number',
  connection_employee_id: 'connection_employee_id'
};

exports.Prisma.restaurantOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  client_id: 'client_id',
  city: 'city',
  google_place_id: 'google_place_id',
  line_one: 'line_one',
  line_two: 'line_two',
  pincode: 'pincode',
  state: 'state'
};

exports.Prisma.vertical_food_employeeOrderByRelevanceFieldEnum = {
  id: 'id',
  first_name: 'first_name',
  last_name: 'last_name',
  country_code: 'country_code',
  mobile_number: 'mobile_number',
  email: 'email',
  password: 'password',
  employee_display_id: 'employee_display_id',
  client_id: 'client_id',
  restaurant_id: 'restaurant_id',
  profile_pic: 'profile_pic'
};

exports.Prisma.vertical_food_employee_boxOrderByRelevanceFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  box_id: 'box_id'
};

exports.Prisma.restaurant_boxOrderByRelevanceFieldEnum = {
  id: 'id',
  restaurant_id: 'restaurant_id',
  box_id: 'box_id'
};

exports.Prisma.vertical_food_employee_deletedOrderByRelevanceFieldEnum = {
  id: 'id',
  first_name: 'first_name',
  last_name: 'last_name',
  country_code: 'country_code',
  mobile_number: 'mobile_number',
  email: 'email',
  employee_display_id: 'employee_display_id',
  client_name: 'client_name',
  role_name: 'role_name',
  profile_pic: 'profile_pic',
  client_id: 'client_id',
  x_primary_key: 'x_primary_key'
};

exports.Prisma.restaurant_deletedOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  client_id: 'client_id',
  client_name: 'client_name',
  manager_id: 'manager_id',
  manager_name: 'manager_name',
  city: 'city',
  google_place_id: 'google_place_id',
  line_one: 'line_one',
  line_two: 'line_two',
  pincode: 'pincode',
  state: 'state',
  x_primary_key: 'x_primary_key'
};

exports.Prisma.box_deletedOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  box_display_id: 'box_display_id',
  vertical_id: 'vertical_id',
  vertical_name: 'vertical_name',
  client_id: 'client_id',
  client_name: 'client_name',
  vehicle_number: 'vehicle_number',
  x_primary_key: 'x_primary_key'
};

exports.Prisma.vertical_food_consumerOrderByRelevanceFieldEnum = {
  id: 'id',
  full_name: 'full_name',
  country_code: 'country_code',
  phone: 'phone',
  client_id: 'client_id'
};

exports.Prisma.vertical_food_consumer_boxOrderByRelevanceFieldEnum = {
  id: 'id',
  consumer_id: 'consumer_id',
  box_id: 'box_id'
};

exports.Prisma.box_lockOrderByRelevanceFieldEnum = {
  id: 'id',
  box_id: 'box_id'
};

exports.Prisma.notificationOrderByRelevanceFieldEnum = {
  id: 'id',
  client_id: 'client_id',
  box_id: 'box_id',
  box_display_id: 'box_display_id',
  box_name: 'box_name',
  restaurant_name: 'restaurant_name',
  title: 'title',
  description: 'description'
};

exports.Prisma.box_telemetry_latestOrderByRelevanceFieldEnum = {
  id: 'id',
  box_id: 'box_id'
};
exports.employee_status = exports.$Enums.employee_status = {
  active: 'active',
  suspended: 'suspended',
  unassigned: 'unassigned'
};

exports.vertical_status = exports.$Enums.vertical_status = {
  active: 'active',
  deleted: 'deleted'
};

exports.client_status = exports.$Enums.client_status = {
  active: 'active',
  inactive: 'inactive',
  suspended: 'suspended'
};

exports.faq_category_status = exports.$Enums.faq_category_status = {
  active: 'active',
  suspended: 'suspended',
  deleted: 'deleted'
};

exports.faq_question_publishing_status = exports.$Enums.faq_question_publishing_status = {
  draft: 'draft',
  published: 'published'
};

exports.role_status = exports.$Enums.role_status = {
  active: 'active',
  deleted: 'deleted'
};

exports.box_status = exports.$Enums.box_status = {
  active: 'active',
  suspended: 'suspended'
};

exports.restaurant_status = exports.$Enums.restaurant_status = {
  active: 'active',
  suspended: 'suspended'
};

exports.client_employee_role = exports.$Enums.client_employee_role = {
  manager: 'manager',
  delivery: 'delivery'
};

exports.employee_box_status = exports.$Enums.employee_box_status = {
  shared: 'shared',
  blocked: 'blocked'
};

exports.employee_box_access = exports.$Enums.employee_box_access = {
  direct: 'direct',
  public: 'public',
  all_employees: 'all_employees'
};

exports.restaurant_box_status = exports.$Enums.restaurant_box_status = {
  shared: 'shared',
  not_shared: 'not_shared',
  blocked: 'blocked'
};

exports.food_consumer_status = exports.$Enums.food_consumer_status = {
  pending: 'pending',
  delivered: 'delivered',
  cancelled: 'cancelled'
};

exports.box_lock_status = exports.$Enums.box_lock_status = {
  locked: 'locked',
  unlocked: 'unlocked',
  not_available: 'not_available',
  offline: 'offline'
};

exports.notification_type = exports.$Enums.notification_type = {
  warning: 'warning',
  error: 'error',
  success: 'success',
  notification: 'notification'
};

exports.box_health_status = exports.$Enums.box_health_status = {
  critical: 'critical',
  healthy: 'healthy',
  attention: 'attention'
};

exports.hardware_state = exports.$Enums.hardware_state = {
  on: 'on',
  off: 'off',
  unknown: 'unknown'
};

exports.box_connection_status = exports.$Enums.box_connection_status = {
  connected: 'connected',
  disconnected: 'disconnected',
  unknown: 'unknown'
};

exports.Prisma.ModelName = {
  admin: 'admin',
  admin_dismissed: 'admin_dismissed',
  system_config: 'system_config',
  icon: 'icon',
  vertical: 'vertical',
  client: 'client',
  client_deleted: 'client_deleted',
  faq_category: 'faq_category',
  faq_question: 'faq_question',
  faq_question_category: 'faq_question_category',
  role: 'role',
  box: 'box',
  restaurant: 'restaurant',
  vertical_food_employee: 'vertical_food_employee',
  vertical_food_employee_box: 'vertical_food_employee_box',
  restaurant_box: 'restaurant_box',
  vertical_food_employee_deleted: 'vertical_food_employee_deleted',
  restaurant_deleted: 'restaurant_deleted',
  box_deleted: 'box_deleted',
  vertical_food_consumer: 'vertical_food_consumer',
  vertical_food_consumer_box: 'vertical_food_consumer_box',
  box_lock: 'box_lock',
  notification: 'notification',
  box_telemetry_latest: 'box_telemetry_latest'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
