import type { ErrorTemplateMap } from "@/configs/template-types";

export const foodErrorTemplates: ErrorTemplateMap = {
	auth: {
		login: {
			ACCOUNT_NOT_FOUND: {
				message: "No employee can be found!",
				code: 400,
				error_toast_title: "Account not found",
				error_toast_description: "We couldn't find your details. Please contact your restaurant admin.",
			},
			UNAUTHORIZED: {
				message: "You are not authorized to login.",
				code: 403,
				error_toast_title: "Access Denied",
				error_toast_description: "Your role does not have permission to access this portal. If you believe this is an error, please contact your manager.",
			},
			SUSPENDED: {
				message: "Your account has been suspended!",
				code: 403,
				error_toast_title: "Account Suspended",
				error_toast_description: "Your access has been temporarily revoked. Please contact support or your organization administrator for more details.",
			},
			PASSWORD_NOT_SET: {
				message: "Please login using OTP and set a password first.",
				code: 400,
				error_toast_title: "Setup Required",
				error_toast_description: "You haven't set a password yet. Please use the 'Login with OTP' option to access your account for the first time.",
				error_toast_btn_title: "Login with OTP",
				error_toast_btn_action: "/auth/otp-login",
			},
			INVALID_CREDENTIALS: {
				message: "Invalid login credentials.",
				code: 401,
				error_toast_title: "Login Failed",
				error_toast_description: "The password you entered is incorrect. Please try again or reset your password.",
				error_toast_btn_title: "Reset Password",
				error_toast_btn_action: "/auth/forgot-password",
			},
			PASSWORD_INVALID: {
				message: "The current password you entered is incorrect.",
				code: 400,
				error_toast_title: "Verification Failed",
				error_toast_description: "The current password does not match our records. Please try again.",
			},

			OTP_EXPIRED: {
				message: "The OTP has expired. Please request a new one.",
				code: 400,
				error_toast_title: "OTP Expired",
				error_toast_description: "The verification code you entered is no longer valid. Please click 'Resend OTP' to get a new code.",
			},
			OTP_INVALID: {
				message: "The OTP you entered is incorrect.",
				code: 400,
				error_toast_title: "Invalid OTP",
				error_toast_description: "Please try again.",
			},
			OTP_SAVE_FAILED: {
				message: "Failed to save OTP",
				code: 500,
				error_toast_title: "System Busy",
				error_toast_description: "We are having trouble processing your request right now. Please try again in a few minutes.",
			},
			ACCOUNT_INACTIVE: {
				message: "Your account is not active, please contact support",
				code: 400,
				error_toast_title: "Account Restricted",
				error_toast_description: "Your account status prevents login at this time. Please reach out to your administrator for assistance.",
			},
			MAGIC_LINK_SAVE_FAILED: {
				message: "Failed to save reset token",
				code: 500,
				error_toast_title: "System Error",
				error_toast_description: "We couldn't generate your password reset link. Please contact support if this persists.",
			},
			EMAIL_NOT_FOUND: {
				message: "No email found for this account!",
				code: 400,
				error_toast_title: "Setup Required",
				error_toast_description: "This account does not have a primary email address configured. Please contact your organization administrator.",
			},
			AUTH_TOKEN_REQUIRED: {
				message: "Authentication token is required!",
				code: 401,
				error_toast_title: "Session Required",
				error_toast_description: "Your session has expired or is missing. Please log in again to continue.",
			},
			INVALID_AUTH_TOKEN: {
				message: "The auth token is invalid for this request!",
				code: 401,
				error_toast_title: "Security Warning",
				error_toast_description: "The provided security token is not valid for this operation.",
			},
			CREDENTIAL_MISMATCH: {
				message: "The token does not match the provided credentials!",
				code: 401,
				error_toast_title: "Verification Failed",
				error_toast_description: "The security token provided does not match your account information.",
			},
			AUTH_FAILED: {
				message: "Authentication failed!",
				code: 401,
				error_toast_title: "Access Denied",
				error_toast_description: "We could not verify your identity. Please try logging in again.",
			},
			INVALID_OTP_TOKEN: {
				message: "Invalid otp or token!",
				code: 401,
				error_toast_title: "Invalid Link",
				error_toast_description: "The security code or link you used is incorrect or has already been used.",
			},
			MAGIC_LINK_EXPIRED: {
				message: "The reset link is either expired or invalid!",
				code: 400,
				error_toast_title: "Link Expired",
				error_toast_description: "This password reset link is no longer valid. Please request a new link to proceed.",
			},
		},
	},
	restaurant: {
		assign: {
			manager: {
				REASSIGNMENT_CONFLICT: {
					message: "Manager could not be reassigned due to conflicts.",
					code: 409,
					error_toast_title: "Conflict",
					error_toast_description: "The manager could not be reassigned due to conflicts. Other employees have been reassigned.",
					error_toast_btn_title: "View Details",
					error_toast_btn_action: "/food/conflicts/details",
				},
				ACTIVATION_CONFLICT: {
					message: "Some managers could not be reassigned during activation.",
					code: 409,
					error_toast_title: "Conflict",
					error_toast_description: "Some managers could not be reassigned due to conflicts. Their accounts will be reactivated as unassigned.",
					error_toast_btn_title: "View Details",
					error_toast_btn_action: "/food/conflicts/details",
				},
				SUSPENSION_CONFLICT: {
					message: "Some managers could not be reassigned during suspension.",
					code: 409,
					error_toast_title: "Conflict",
					error_toast_description: "Some managers could not be reassigned due to conflicts. Their accounts has been marked as unassigned.",
					error_toast_btn_title: "View Details",
					error_toast_btn_action: "/food/conflicts/details",
				},
				INVALID_ROLE: {
					message: "Only employees with the role 'manager' can be assigned.",
					code: 400,
					error_toast_title: "Invalid Role",
					error_toast_description: "The selected employee's current role is not 'manager'. Please update their role before assigning them as a restaurant lead.",
					error_toast_btn_title: "Update Role",
					error_toast_btn_action: "/food/employee/details?id={id}",
				},
				RESTAURANT_NOT_FOUND: {
					message: "Restaurant not found.",
					code: 404,
					error_toast_title: "Missing Resource",
					error_toast_description: "The restaurant you are trying to modify could not be located in your client scope.",
				},
				ACCESS_DENIED: {
					message: "Access denied: The requested resource is outside your vertical's scope.",
					code: 403,
					error_toast_title: "Access Denied",
					error_toast_description: "You do not have permission to access resources outside your assigned client organization.",
				},
			},
			transfer: {
				INVALID_PASSWORD: {
					message: "Invalid password. Authorization failed.",
					code: 401,
					error_toast_title: "Authorization Failed",
					error_toast_description: "The password you provided is incorrect. Please verify and try again.",
				},
				RECIPIENT_NOT_FOUND: {
					message: "Recipient employee not found.",
					code: 404,
					error_toast_title: "Recipient Not Found",
					error_toast_description: "We couldn't find the employee record for the transfer recipient.",
				},
				ORGANIZATION_MISMATCH: {
					message: "Recipient does not belong to your organization.",
					code: 403,
					error_toast_title: "Transfer Restricted",
					error_toast_description: "Ownership can only be transferred to employees within your own client organization.",
				},
			},
		},
		resource: {
			NOT_FOUND: {
				message: "No restaurants found to delete",
				code: 404,
				error_toast_title: "Deletion Error",
				error_toast_description: "The selected restaurants could not be found for deletion.",
			},
			PARTIAL_FOUND: {
				message: "Some restaurants were not found or already deleted.",
				code: 400,
				error_toast_title: "Bulk Operation Warning",
				error_toast_description: "Not all selected restaurants could be processed. Some IDs may be invalid or belong to another scope.",
			},
			REASSIGNMENT_TO_NON_ACTIVE: {
				message: "can not reassign resources to non active restaurant",
				code: 400,
				error_toast_title: "Invalid Destination",
				error_toast_description: "Resources can only be reassigned to active restaurants.",
			},
		},
	},
	box: {
		NOT_FOUND: {
			message: "No such box found!",
			code: 404,
			error_toast_title: "Box Not Found",
			error_toast_description: "The requested GrubPac could not be found in our database.",
		},
		CLIENT_ASSIGNED: {
			message: "A client is already assigned to this box.",
			code: 400,
			error_toast_title: "Active Assignment",
			error_toast_description: "This box is currently assigned to a client. Please reassign or unassign it before deletion.",
		},
		BULK_CLIENT_ASSIGNED: {
			message: "Some boxes already have clients assigned.",
			code: 400,
			error_toast_title: "Bulk Deletion Error",
			error_toast_description: "You cannot delete boxes that are currently assigned to clients. Please review and reassign them first.",
		},
		VERTICAL_MISMATCH: {
			message: "You must assign box that matches the client vertical",
			code: 400,
			error_toast_title: "Vertical Conflict",
			error_toast_description: "The selected box does not match the organization's business vertical.",
		},
		ALREADY_SUSPENDED: {
			message: "All selected boxes are already suspended.",
			code: 400,
			error_toast_title: "Redundant Action",
			error_toast_description: "The selected GrubPacs are already in a suspended state.",
		},
		ALREADY_ACTIVE: {
			message: "All selected boxes are already active.",
			code: 400,
			error_toast_title: "Redundant Action",
			error_toast_description: "The selected GrubPacs are already active and operational.",
		},
	},
	account: {
		PASSWORD_NOT_SET: {
			message: "Password not set for this account. Please set a password first.",
			code: 400,
			error_toast_title: "Setup Required",
			error_toast_description: "Your account does not have a password configured. Please set one before proceeding with this action.",
		},
		NO_CHANGE_REQUESTS: {
			message: "No change requests exist to verify.",
			code: 400,
			error_toast_title: "No Request Found",
			error_toast_description: "We couldn't find any pending profile updates to verify. Please try updating your details again.",
		},
	},
	common: {
		VERTICAL_NOT_FOUND: {
			message: "No food vertical found!",
			code: 400,
			error_toast_title: "System Error",
			error_toast_description: "The application configuration for the food vertical is missing. Please contact system administration.",
		},
		EMPLOYEE_NOT_FOUND: {
			message: "Employee not found!",
			code: 404,
			error_toast_title: "Missing Resource",
			error_toast_description: "The employee record you are looking for could not be found.",
		},
		EMAIL_ALREADY_EXISTS: {
			message: "This email is already registered with another account!",
			code: 400,
			error_toast_title: "Duplicate Email",
			error_toast_description: "An account with this email address already exists. Please use a different email or login to your existing account.",
		},
		MOBILE_ALREADY_EXISTS: {
			message: "An employee with this mobile number already exists",
			code: 400,
			error_toast_title: "Duplicate Mobile",
			error_toast_description: "This mobile number is already associated with another account.",
		},
		DISPLAY_ID_ALREADY_EXISTS: {
			message: "An employee with this display ID already exists",
			code: 400,
			error_toast_title: "Duplicate Display ID",
			error_toast_description: "The provided employee display ID is already in use.",
		},
		ACCESS_DENIED: {
			message: "Access denied: The requested resource is outside your vertical's scope.",
			code: 403,
			error_toast_title: "Access Denied",
			error_toast_description: "You do not have permission to access or modify this resource.",
		},
		SUPER_ADMIN_EMAIL_CONFLICT: {
			message: "You cannot have the same email as the super admin",
			code: 400,
			error_toast_title: "Email Conflict",
			error_toast_description: "This email address is reserved for the Super Administrator account.",
		},
		RESTAURANT_HAS_MANAGER: {
			message: "This restaurant already has a manager! Please unassign his role first",
			code: 400,
			error_toast_title: "Assignment Conflict",
			error_toast_description: "This restaurant already has an active manager assigned. You must unassign the current manager before assigning a new one.",
		},
		RESTAURANT_OWNERSHIP_MISMATCH: {
			message: "This restaurant does not belong to the same owner!",
			code: 400,
			error_toast_title: "Ownership Error",
			error_toast_description: "You can only assign employees to restaurants within your own organization.",
		},
	},
};
