# docker-compose.yml
services:
  mysql:
    image: mysql:8.0
    container_name: grub-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: grub_db
      MYSQL_USER: grub_user
      MYSQL_PASSWORD: StrongUserPass@123 # Raw password for container config
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_net

  mongo:
    image: mongo:6.0
    container_name: grub-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_root
      MONGO_INITDB_ROOT_PASSWORD: StrongMongoRoot@123 # Raw password for container config
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - db_net


volumes:
  mysql_data:
  mongo_data:

networks:
  frontend_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
  backend_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
  db_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
