name: Development Build

on:
    push:
        branches:
            - ankan_dev

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRODUCTION_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519

            - name: Add EC2 host to known_hosts
              run: |
                  ssh-keyscan -t ed25519 -H ${{ secrets.SSH_PRODUCTION_HOST }} >> ~/.ssh/known_hosts

            - name: Build & Deploy
              run: |
                  ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_PRODUCTION_USER_NAME }}@${{ secrets.SSH_PRODUCTION_HOST }} << 'EOF'
                    source ~/.zshrc
                    source ~/.bashrc
                    source ~/.profile
                    ls
                    cd grubpac_api
                    git stash
                    git pull origin ankan_dev
                    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" && \
                    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
                    export BUN_INSTALL="$HOME/.bun" && \
                    export PATH="$BUN_INSTALL/bin:$PATH" && \
                    source ~/.bashrc && \
                    /home/ubuntu/.bun/bin/bun install && \
                    /home/ubuntu/.bun/bin/bun db:push && \
                    /home/ubuntu/.bun/bin/bun db:generate && \
                    /home/ubuntu/.nvm/versions/node/v22.20.0/bin/pm2 list && \
                    /home/ubuntu/.nvm/versions/node/v22.20.0/bin/pm2 restart "${{ secrets.PRODUCTION_PM2_ID }}" && \
                    /home/ubuntu/.nvm/versions/node/v22.20.0/bin/pm2 list

            - name: Done
              run: |
                  echo "Build Done"
